### ISSUE TITLE
Add README file to skelet repository

### ISSUE THREAD

**Issue by champsupertramp** [PressApps/skelet#1]
Add README file to skelet repository explaining a new developer how it works:
- adding to project
- config files
- pulling values

**Comment by champsupertramp** [comment]
@chromjak  i just moved this task from trello.

**Comment by ivanchromjak** [comment]
is this still in progress?

**Comment by champsupertramp** [comment]
@chromjak  I'd like to know how are we going to credits other developers and contributors?

**Comment by ivanchromjak** [comment]
@champsupertramp its one sentence, done/committed.
