### ISSUE TITLE
Submenu fix

### ISSUE THREAD

**Issue by ivanchromjak** [PressApps/skelet#3]
Load first tab on parent tab click http://d.pr/i/1jFCv

Sample options: https://gist.github.com/chromjak/dfa4d3ed7753911168ef

**Comment by ivanchromjak** [comment]
Changes:
- [x] When we click a tab with submenu, the submenu is displayed (ggod), but when we click other tab the menu should hide
- [x] When we click a tab with submenu, the submenu is displayed, but the second click on the active tab should do nothing (now it hides submenu)

**Comment by ivanchromjak** [comment]
http://d.pr/i/11uf6

**Comment by champsupertramp** [comment]
please sync my latest commit in feedback. It's not a Skelet issue.
