### ISSUE TITLE
Issue on default value when values are not stored on the DB

### ISSUE THREAD

**Issue by junrillg** [PressApps/skelet#5]
@chromjak I don't know if you recognized this issue but everytime we try to create a new **framework option** and check on the value on it even if it has a default it will output an array. I think this is an issue related to the fresh install of the plugin pressapps/pressapps-fullscreen-login#27
![image](https://cloud.githubusercontent.com/assets/5255554/10328880/82c043ac-6cec-11e5-914e-898a9df0fbae.png)

**Comment by champsupertramp** [comment]
I've added the prefixes to avoid conflicts with other pressapps plugins.
